name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release zip
        run: |
          cd custom_components/acit_thermacec
          zip -r ../../acit_thermacec.zip ./*

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./acit_thermacec.zip
          asset_name: acit_thermacec.zip
          asset_content_type: application/zip

